### ISSUE TITLE
Berto_Cloud.c4z Ionic.Zip.ZipException: Could not read

### ISSUE THREAD

**Issue by skinner6695** [davidmassot/Berto#1]
Error when adding the Berto_Cloud.c4z to the Drivers/Virtual folder, or adding within Composer via Add Driver 

Composer appPro - Version: 2.10.5.554601-res

From the log
Berto_Cloud.c4z
Ionic.Zip.ZipException: Could not read\Berto_Cloud.c4z as a zip file ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x0A0A0A0A) at position  0x00000000
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile._InitInstance(String zipFileName, TextWriter statusMessageWriter)
   at Ionic.Zip.ZipFile..ctor(String fileName)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile..ctor(String fileName)
   at Control4.Client.ConfigInfo.FromFile(String file, Boolean restoreProject)
2019-02-18 14:42:24,201 [1   ] ERROR Control4.Client.FileManager - Load Image Failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Control4.Client.FileManager.LoadImage(String relativePath, Boolean imageFromC4z, String driverPath)
2019-02-18 14:42:32,635 [1   ] ERROR Control4.Client.FileManager - Load Image Failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Control4.Client.FileManager.LoadImage(String relativePath, Boolean imageFromC4z, String driverPath)
2019-02-18 14:42:32,843 [1   ] ERROR Control4.Client.FileManager - Load Image Failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Control4.Client.FileManager.LoadImage(String relativePath, Boolean imageFromC4z, String driverPath)
2019-02-18 14:42:32,984 [1   ] ERROR Control4.Client.FileManager - Load Image Failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Control4.Client.FileManager.LoadImage(String relativePath, Boolean imageFromC4z, String driverPath)
2019-02-18 14:44:08,516 [6   ] WARN  Control4.Client.ConfigDataManager - Error communicating with Solr.
System.Net.WebException: The request was aborted: The operation has timed out.
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Net.WebClient.OpenRead(String address)
   at Control4.Client.ConfigDataManager.GetOnlineDriverVersion(String filename)

**Comment by davidmassot** [comment]
Looks like a problem with the download. The file should be in ZIP format despite having a .c4z extension. Rename to .zip and see if you can Unzip, alternatively re-download.

**Comment by skinner6695** [comment]
Thank you. I downloaded the whole repo as a zip, then uploaded the .c4z to Composer successfully. Oddly a direct download of the .c4z twice did not work.
